CREATE TABLE opencts_streets (
id SERIAL UNIQUE,
uid TEXT NOT NULL UNIQUE DEFAULT lpad(md5(random()::text), 16),
title TEXT NOT NULL UNIQUE,
tile BYTEA NOT NULL,
paths TEXT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP,
PRIMARY KEY (id)
);

CREATE TABLE opencts_autobuses (
id SERIAL UNIQUE,
uid TEXT NOT NULL UNIQUE DEFAULT lpad(md5(random()::text), 16),
title TEXT NOT NULL UNIQUE,
seats INTEGER NOT NULL,
standing INTEGER NOT NULL,
a BYTEA NOT NULL,
b BYTEA NOT NULL,
c BYTEA NOT NULL,
d BYTEA NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP,
PRIMARY KEY (id)
);

COMMIT;
